# Generated by Django 5.2.8 on 2025-11-18 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(4)])),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
            ],
        ),
    ]
